const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const VALID_DAYS=["Mandag","Tirsdag","Onsdag","Torsdag","Fredag","Lørdag","Søndag"];
async function ensureTables(env){
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS checklist (week TEXT NOT NULL,item_id TEXT NOT NULL,checked INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (week,item_id))").run();
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS preferences (id INTEGER PRIMARY KEY CHECK (id=1),selected_days TEXT NOT NULL,day_requests TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 try{await env.DB.prepare("ALTER TABLE preferences ADD COLUMN day_requests TEXT NOT NULL DEFAULT '{}'").run()}catch{}
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS manual_items (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,checked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
}
async function checklistGet(request,env){const week=new URL(request.url).searchParams.get("week");if(!week)return json({error:"week is required"},400);const r=await env.DB.prepare("SELECT item_id,checked FROM checklist WHERE week=?").bind(week).all();return json({week,checked:Object.fromEntries(r.results.map(x=>[x.item_id,Boolean(x.checked)]))});}
async function checklistPost(request,env){const b=await request.json().catch(()=>null);if(!b||typeof b.week!=="string"||typeof b.itemId!=="string"||typeof b.checked!=="boolean")return json({error:"invalid payload"},400);await env.DB.prepare("INSERT INTO checklist (week,item_id,checked,updated_at) VALUES (?,?,?,datetime('now')) ON CONFLICT(week,item_id) DO UPDATE SET checked=excluded.checked,updated_at=datetime('now')").bind(b.week,b.itemId,b.checked?1:0).run();return json({ok:true});}
async function checklistDelete(request,env){const b=await request.json().catch(()=>null);if(!b||typeof b.week!=="string")return json({error:"invalid payload"},400);await env.DB.prepare("DELETE FROM checklist WHERE week=?").bind(b.week).run();return json({ok:true});}
async function preferencesGet(env){await ensureTables(env);const row=await env.DB.prepare("SELECT selected_days,day_requests,updated_at FROM preferences WHERE id=1").first();if(!row)return json({configured:false,selectedDays:[]});let d=[];try{d=JSON.parse(row.selected_days)}catch{}let requests={};try{requests=JSON.parse(row.day_requests||"{}")}catch{};const cleanRequests=Object.fromEntries(VALID_DAYS.filter(day=>typeof requests[day]==="string"&&requests[day].trim()).map(day=>[day,requests[day].trim().slice(0,120)]));return json({configured:true,selectedDays:d.filter(x=>VALID_DAYS.includes(x)),dayRequests:cleanRequests,updatedAt:row.updated_at});}
async function preferencesPost(request,env){await ensureTables(env);const b=await request.json().catch(()=>null);if(!b||!Array.isArray(b.selectedDays))return json({error:"invalid payload"},400);const d=VALID_DAYS.filter(x=>b.selectedDays.includes(x));if(!d.length)return json({error:"select at least one day"},400);const requests=b.dayRequests&&typeof b.dayRequests==="object"?Object.fromEntries(VALID_DAYS.filter(day=>typeof b.dayRequests[day]==="string"&&b.dayRequests[day].trim()).map(day=>[day,b.dayRequests[day].trim().slice(0,120)])):{};await env.DB.prepare("INSERT INTO preferences (id,selected_days,day_requests,updated_at) VALUES (1,?,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET selected_days=excluded.selected_days,day_requests=excluded.day_requests,updated_at=datetime('now')").bind(JSON.stringify(d),JSON.stringify(requests)).run();return json({ok:true,selectedDays:d,dayRequests:requests});}
async function manualGet(env){await ensureTables(env);const r=await env.DB.prepare("SELECT id,name,checked FROM manual_items ORDER BY id").all();return json({items:r.results.map(x=>({...x,checked:Boolean(x.checked)}))});}
async function manualPost(request,env){await ensureTables(env);const b=await request.json().catch(()=>null);const name=typeof b?.name==="string"?b.name.trim().slice(0,100):"";if(!name)return json({error:"name is required"},400);const r=await env.DB.prepare("INSERT INTO manual_items (name) VALUES (?) RETURNING id,name,checked").bind(name).first();return json({item:{...r,checked:false}},201);}
async function manualPatch(request,env){await ensureTables(env);const b=await request.json().catch(()=>null);if(!Number.isInteger(b?.id)||typeof b.checked!=="boolean")return json({error:"invalid payload"},400);await env.DB.prepare("UPDATE manual_items SET checked=?,updated_at=datetime('now') WHERE id=?").bind(b.checked?1:0,b.id).run();return json({ok:true});}
async function manualDelete(request,env){await ensureTables(env);const b=await request.json().catch(()=>null);if(!Number.isInteger(b?.id))return json({error:"invalid payload"},400);await env.DB.prepare("DELETE FROM manual_items WHERE id=?").bind(b.id).run();return json({ok:true});}
export default{async fetch(request,env){if(!env.DB)return request.method==="GET"&&new URL(request.url).pathname.startsWith("/api/")?json({error:"database unavailable"},503):env.ASSETS.fetch(request);const u=new URL(request.url);
 if(u.pathname==="/api/checklist"){if(request.method==="GET")return checklistGet(request,env);if(request.method==="POST")return checklistPost(request,env);if(request.method==="DELETE")return checklistDelete(request,env);}
 if(u.pathname==="/api/preferences"){if(request.method==="GET")return preferencesGet(env);if(request.method==="POST")return preferencesPost(request,env);}
 if(u.pathname==="/api/manual-items"){if(request.method==="GET")return manualGet(env);if(request.method==="POST")return manualPost(request,env);if(request.method==="PATCH")return manualPatch(request,env);if(request.method==="DELETE")return manualDelete(request,env);}
 if(u.pathname==="/proxy/flyer-page"&&request.method==="GET"){const asset=(u.searchParams.get("asset")||"").replace(/[^A-Za-z0-9_-]/g,""),page=Math.max(1,parseInt(u.searchParams.get("page")||"1",10));if(!asset||!Number.isFinite(page))return new Response("Bad request",{status:400});const source="s3://sgn-prd-assets/uploads/"+asset+"/p-"+page+".webp";const target="https://image-transformer-api.tjek.com/?u="+encodeURIComponent(source)+"&w=1200";const r=await fetch(target,{headers:{"user-agent":"Mozilla/5.0","accept":"image/avif,image/webp,image/*,*/*;q=0.8"}});if(!r.ok)return new Response("Flyer page unavailable",{status:r.status});return new Response(r.body,{headers:{"content-type":r.headers.get("content-type")||"image/webp","cache-control":"public, max-age=86400"}});}
 if(u.pathname==="/proxy/coop-flyer"&&request.method==="GET"){const store=u.searchParams.get("store");const target=store==="365discount"?"https://365discount.coop.dk/365avis/":store==="SuperBrugsen"?"https://superbrugsen.coop.dk/avis/":null;if(!target)return new Response("Unknown store",{status:400});const upstream=await fetch(target,{headers:{"user-agent":"Mozilla/5.0"}});let html=await upstream.text();const origin=new URL(target).origin;html=html.replace(/<meta[^>]+http-equiv=["'](?:content-security-policy|x-frame-options)["'][^>]*>/gi,"");html=html.replace(/<head([^>]*)>/i,'<head$1><base href="'+origin+'/"><meta name="referrer" content="no-referrer">');html=html.replace(/(["'(=])\/(?!\/)/g,'$1'+origin+'/');return new Response(html,{status:upstream.status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-security-policy":"frame-ancestors 'self'"}})}
 if(u.pathname.startsWith("/api/"))return json({error:"method not allowed"},405);return env.ASSETS.fetch(request);}};